//This is the svg pattern you should be matching, without using any x or y coordinates. 

const modelSvg = d3.select("body").append("svg")
                    .attr("width", 250)
                    .attr("height", 250)
                    .style("border", "1px solid black")

modelSvg.append("rect")
        .attr("width", 50)
        .attr("height", 50)
        .attr("x", 0)
        .attr("y", 0)


modelSvg.append("rect")
        .attr("width", 50)
        .attr("height", 50)
        .attr("x", 100)
        .attr("y", 0)


modelSvg.append("rect")
        .attr("width", 50)
        .attr("height", 50)
        .attr("x", 200)
        .attr("y", 0)

modelSvg.append("rect")
        .attr("width", 50)
        .attr("height", 50)
        .attr("x", 100)
        .attr("y", 100)
        

modelSvg.append("rect")
        .attr("width", 50)
        .attr("height", 50)
        .attr("x", 200)
        .attr("y", 200)
modelSvg.append("rect")
        .attr("width", 50)
        .attr("height", 50)
        .attr("x", 100)
        .attr("y", 200)
modelSvg.append("rect")
        .attr("width", 50)
        .attr("height", 50)
        .attr("x", 0)
        .attr("y", 200)

modelSvg.append("circle")
        .attr("cy", 0)
        .attr("cx", 0)
        .attr("r",25)
        .style("fill", "pink")
modelSvg.append("circle")
        .attr("cy", 100)
        .attr("cx", 100)
        .attr("r",25)
        .style("fill", "pink")
modelSvg.append("circle")
        .attr("cy", 0)
        .attr("cx", 100)
        .attr("r",25)
        .style("fill", "pink")
modelSvg.append("circle")
        .attr("cy", 200)
        .attr("cx", 0)
        .attr("r",25)
        .style("fill", "pink")
modelSvg.append("circle")
        .attr("cy", 0)
        .attr("cx", 200)
        .attr("r",25)
        .style("fill", "pink")

modelSvg.append("circle")
        .attr("cy", 200)
        .attr("cx", 100)
        .attr("r",25)
        .style("fill", "pink")

modelSvg.append("circle")
        .attr("cy", 200)
        .attr("cx", 200)
        .attr("r",25)
        .style("fill", "pink")


